### ISSUE TITLE
when npm install got error bufferutil

### ISSUE THREAD

**Issue by herdidi47** [marcsances/td#29] opened 2020-12-20 23:54 UTC
log attached
[2020-12-20T23_48_00_216Z-debug.log](https://github.com/marcsances/td/files/5721707/2020-12-20T23_48_00_216Z-debug.log)

**Comment by marcsances** [comment] 2020-12-28 15:51
Thanks for reporting. I could reproduce the same issue on my Windows machine -apologies for that, I'm not actively working on this project anymore.

I'm working on a fix, when that's fixed I'll let you know.

**Comment by marcsances** [comment] 2020-12-28 17:11
Alright, I've rebased with the latest Electron seed and now it should boot again.

However, this has lead into me finding that currently the RPC integration is not working due to deprecation. I've created issue #33 to address it, I've tried resolving it by moving to GameSDK but couldn't fix it yet.

I attach here the explanation. I will close this issue since it should be resolved in master, if the npm install fails again, please reopen with a crash log and the environment you use (Windows version + NodeJS). Please notice Visual C++ build tools and Python 3 are required for development.

## Current Status (28-12-2020)

Apparently Discord RPC has now been deprecated in favor of GameSDK. Moreover, RPC scopes are now whitelist only, so we cannot authenticate.

Therefore, this seed is currently failing to show the current Rich Presence status due to the changes made to Discord APIs.

I am working on integrating the new SDK (which seems not to be whitelist only), but I cannot provide a deadline yet.

It is implemented already, but the SDK initialization returns me "false" so I will keep investigating whenever I have time for it.

Feel free to use this project as a seed for integrating the current SDKs. Here's the reference material:

* [Rich Presence](https://discord.com/developers/docs/rich-presence/best-practices)
* [Discord GameSDK for Electron](https://github.com/open-unlight/node-discord-game)

If you manage to fix this issue, feel free to open a pull request.

**Closed by marcsances** 2020-12-28 17:11 UTC
Labels: reviewing
